title: Tokyo Area Planetary Science
description: ...or anything under the deuterium-burning mass limit
logo: planets.png
theme: jekyll-theme-minimal
is_user_page: false
is_project_page: false
show_downloads: true
